### PR TITLE
Updated to match 2013 honor code revision

### PR DESCRIPTION
**Pull request by mchua**
These are patches reflecting the Honor Code amendments Jeff Holzgrafe recently sent out to the Alumni list. They're accurate as regards the core values, but I don't know if the intro changed (or if any surrounding text of the honor code is there as well).

### CODE REVIEW

**Comment by tcr** [comment]
Thanks, Mel! Remind me to go through and forcibly alter the Git history to reflect real dates and amendments.

**Comment by mchua** [comment]
On 4/23/2013 2:36 PM, Tim Cameron Ryan wrote:

> Thanks, Mel! Remind me to go through and forcibly alter the Git history
> to reflect real dates and amendments.

This is a reminder to go through and forcibly alter, etc... :)

(or rather, how/when would you like to be reminded?)

--Mel

**Comment by tcr** [comment]
@mchua Found what I was looking for: http://www-cs-students.stanford.edu/~blynn/gitmagic/ch05.html The question is how best to structure the original honor code as a commit and what date should be attributed to it. Is there a specific date at which the honor code was ratified? And should I break it up by individual codes (like you've done here, which is pretty sweet)

**Comment by mchua** [comment]
Am 28.04.2013 20:25, schrieb Tim Cameron Ryan:

> @mchua https://github.com/mchua Found what I was looking for:
> http://www-cs-students.stanford.edu/~blynn/gitmagic/ch05.html

Yes. Git rebase is MAGICAL.

> question is how best to structure the original honor code as a
> commit and what date should be attributed to it. Is there a specific
> date at which the honor code was ratified?

If memory serves me, Olin's original honor code was ratified sometime
during Partner Year, most likely in Spring 2002. Trustee Susan Fredholm
Murphy is a former HB chair and might know; Rod Crafts (catch him while
you can!) will almost certainly have the exact date somewhere, if the 
current HB does not have it in their history files.

> And should I break it up by individual codes (like you've done here,
> which is pretty sweet)

This is personal sentiment, but I think the first version should be an 
initial commit (all 5 codes at once) since it really did get ratified as 
a unified document, and then revisions should be one code at a time to 
better show the granularity of changes (with the commit date linking 
them together).

What would be _really_ interesting is if the current HB, or Rod/Student 
Life, or the original HB members (ask Susan) had even earlier drafts of 
the honor code, because then you could show the alpha/beta versions 
pre-gold-master-1.0, all the branches that we could have gone down but 
did not, etc. But that's... probably more involved than you want to get, 
I'm guessing.

Thanks for putting the code up! It would be pretty awesome if we could 
do this for other classic Olin documents too (mission statement? what 
would curriculum revisions look like on github? Hrm).

**Pull request merged**
